// AUTO-GENERATED list of selectable list icons. ~299 curated Lucide
// icons grouped by category for the ListEditor picker. To add icons, extend the
// arrays here — getListIcon() and the picker pick them up automatically.
import {
  ListChecks, ListTodo, CheckCheck, ClipboardList, ClipboardCheck, Home,
  House, BedDouble, Bed, Bath, ShowerHead, Sofa,
  Armchair, Lamp, DoorOpen, DoorClosed, Key, Trash2,
  Recycle, WashingMachine, Refrigerator, CookingPot, Utensils, UtensilsCrossed,
  Brush, Paintbrush, SprayCan, Plug, Lightbulb, Fan,
  Thermometer, CalendarDays, CalendarCheck, Bell, Clock, AlarmClock,
  StickyNote, NotebookPen, Pin, Flag, Star, Bookmark,
  ChefHat, Apple, Banana, Cherry, Grape, Citrus,
  Carrot, Salad, Soup, Beef, Drumstick, Ham,
  Fish, Egg, EggFried, Pizza, Sandwich, Croissant,
  Cake, CakeSlice, Cookie, Candy, Donut, IceCream,
  IceCreamCone, Popcorn, Wheat, Milk, Coffee, CupSoda,
  Wine, Beer, Martini, GlassWater, Nut, Bean,
  Vegan, ShoppingBag, ShoppingCart, ShoppingBasket, Store, Tag,
  Tags, Receipt, CreditCard, Wallet, Gift, Package,
  PackageOpen, Barcode, ScanBarcode, Shirt, Footprints, Gem,
  Watch, Glasses, Crown, Plane, PlaneTakeoff, PlaneLanding,
  Car, CarFront, Bus, Train, TramFront, Ship,
  Sailboat, Bike, MapPin, Map, Globe, Compass,
  Luggage, Briefcase, Tent, Mountain, MountainSnow, Palmtree,
  TreePalm, Sun, Umbrella, Camera, Ticket, Hotel,
  Fuel, ParkingCircle, GraduationCap, BookOpen, Book, Library,
  PenTool, Pencil, Pen, Ruler, Calculator, Laptop,
  Monitor, Presentation, Building, Building2, Factory, Mailbox,
  Mail, Phone, Printer, Paperclip, Folder, FolderOpen,
  FileText, Files, Award, Trophy, Target, Microscope,
  FlaskConical, Atom, Brain, Dumbbell, HeartPulse, Activity,
  PersonStanding, Pill, Stethoscope, Syringe, Cross, BriefcaseMedical,
  Eye, Bone, Moon, Droplet, Droplets, Flame,
  Timer, Medal, Heart, Baby, Users, User,
  UserRound, CircleUserRound, PawPrint, Dog, Cat, Bird,
  Rabbit, Turtle, Bug, Squirrel, Rat, Snail,
  Smile, HandHeart, Handshake, PartyPopper, Gamepad2, Music,
  Music2, Music4, Headphones, Mic, Guitar, Piano,
  Drum, Radio, Tv, Film, Clapperboard, Image,
  Palette, PaintBucket, Scissors, Puzzle, Dices, Club,
  Spade, Diamond, Flower, Flower2, Sprout, Cloud,
  CloudRain, CloudSnow, CloudLightning, Snowflake, Wind, Rainbow,
  Leaf, Trees, TreePine, TreeDeciduous, Waves, Sunrise,
  Sunset, Sparkles, Zap, Tornado, Smartphone, Tablet,
  Wifi, Bluetooth, Battery, Cpu, HardDrive, Database,
  Server, Mouse, Keyboard, Router, Usb, Webcam,
  Bot, Code, Terminal, Wrench, Hammer, Drill,
  Axe, Pickaxe, Shovel, PaintRoller, Pipette, Cog,
  Settings, Bolt, Magnet, Construction, HardHat, Banknote,
  Coins, DollarSign, PiggyBank, Landmark, TrendingUp, TrendingDown,
  BadgeDollarSign, HandCoins, CircleDollarSign, Rocket, Anchor, Feather,
  Infinity, ThumbsUp, Check, CircleCheck, Circle, Square,
  Triangle, Hexagon, Shield, Lock, Unlock, Search,
  Filter, Wand2, Crosshair, Hourglass, Calendar,
} from 'lucide-react';

export type ListIconType = typeof ListChecks;

export interface ListIconDef {
  name: string;
  Icon: ListIconType;
  category: string;
  keywords: string;
}

export const ICON_CATEGORIES: string[] = ["Tasks & home","Food & drink","Shopping","Travel","Work & school","Health & fitness","Family & pets","Hobbies & leisure","Nature & weather","Tech & devices","Tools & DIY","Money","Symbols & misc"];

export const ICON_OPTIONS: ListIconDef[] = [
  { name: 'ListChecks', Icon: ListChecks, category: "Tasks & home", keywords: "list checks" },
  { name: 'ListTodo', Icon: ListTodo, category: "Tasks & home", keywords: "list todo" },
  { name: 'CheckCheck', Icon: CheckCheck, category: "Tasks & home", keywords: "check check" },
  { name: 'ClipboardList', Icon: ClipboardList, category: "Tasks & home", keywords: "clipboard list" },
  { name: 'ClipboardCheck', Icon: ClipboardCheck, category: "Tasks & home", keywords: "clipboard check" },
  { name: 'Home', Icon: Home, category: "Tasks & home", keywords: "home" },
  { name: 'House', Icon: House, category: "Tasks & home", keywords: "house" },
  { name: 'BedDouble', Icon: BedDouble, category: "Tasks & home", keywords: "bed double" },
  { name: 'Bed', Icon: Bed, category: "Tasks & home", keywords: "bed" },
  { name: 'Bath', Icon: Bath, category: "Tasks & home", keywords: "bath" },
  { name: 'ShowerHead', Icon: ShowerHead, category: "Tasks & home", keywords: "shower head" },
  { name: 'Sofa', Icon: Sofa, category: "Tasks & home", keywords: "sofa" },
  { name: 'Armchair', Icon: Armchair, category: "Tasks & home", keywords: "armchair" },
  { name: 'Lamp', Icon: Lamp, category: "Tasks & home", keywords: "lamp" },
  { name: 'DoorOpen', Icon: DoorOpen, category: "Tasks & home", keywords: "door open" },
  { name: 'DoorClosed', Icon: DoorClosed, category: "Tasks & home", keywords: "door closed" },
  { name: 'Key', Icon: Key, category: "Tasks & home", keywords: "key" },
  { name: 'Trash2', Icon: Trash2, category: "Tasks & home", keywords: "trash 2" },
  { name: 'Recycle', Icon: Recycle, category: "Tasks & home", keywords: "recycle" },
  { name: 'WashingMachine', Icon: WashingMachine, category: "Tasks & home", keywords: "washing machine" },
  { name: 'Refrigerator', Icon: Refrigerator, category: "Tasks & home", keywords: "refrigerator" },
  { name: 'CookingPot', Icon: CookingPot, category: "Tasks & home", keywords: "cooking pot" },
  { name: 'Utensils', Icon: Utensils, category: "Tasks & home", keywords: "utensils" },
  { name: 'UtensilsCrossed', Icon: UtensilsCrossed, category: "Tasks & home", keywords: "utensils crossed" },
  { name: 'Brush', Icon: Brush, category: "Tasks & home", keywords: "brush" },
  { name: 'Paintbrush', Icon: Paintbrush, category: "Tasks & home", keywords: "paintbrush" },
  { name: 'SprayCan', Icon: SprayCan, category: "Tasks & home", keywords: "spray can" },
  { name: 'Plug', Icon: Plug, category: "Tasks & home", keywords: "plug" },
  { name: 'Lightbulb', Icon: Lightbulb, category: "Tasks & home", keywords: "lightbulb" },
  { name: 'Fan', Icon: Fan, category: "Tasks & home", keywords: "fan" },
  { name: 'Thermometer', Icon: Thermometer, category: "Tasks & home", keywords: "thermometer" },
  { name: 'CalendarDays', Icon: CalendarDays, category: "Tasks & home", keywords: "calendar days" },
  { name: 'CalendarCheck', Icon: CalendarCheck, category: "Tasks & home", keywords: "calendar check" },
  { name: 'Bell', Icon: Bell, category: "Tasks & home", keywords: "bell" },
  { name: 'Clock', Icon: Clock, category: "Tasks & home", keywords: "clock" },
  { name: 'AlarmClock', Icon: AlarmClock, category: "Tasks & home", keywords: "alarm clock" },
  { name: 'StickyNote', Icon: StickyNote, category: "Tasks & home", keywords: "sticky note" },
  { name: 'NotebookPen', Icon: NotebookPen, category: "Tasks & home", keywords: "notebook pen" },
  { name: 'Pin', Icon: Pin, category: "Tasks & home", keywords: "pin" },
  { name: 'Flag', Icon: Flag, category: "Tasks & home", keywords: "flag" },
  { name: 'Star', Icon: Star, category: "Tasks & home", keywords: "star" },
  { name: 'Bookmark', Icon: Bookmark, category: "Tasks & home", keywords: "bookmark" },
  { name: 'ChefHat', Icon: ChefHat, category: "Food & drink", keywords: "chef hat" },
  { name: 'Apple', Icon: Apple, category: "Food & drink", keywords: "apple" },
  { name: 'Banana', Icon: Banana, category: "Food & drink", keywords: "banana" },
  { name: 'Cherry', Icon: Cherry, category: "Food & drink", keywords: "cherry" },
  { name: 'Grape', Icon: Grape, category: "Food & drink", keywords: "grape" },
  { name: 'Citrus', Icon: Citrus, category: "Food & drink", keywords: "citrus" },
  { name: 'Carrot', Icon: Carrot, category: "Food & drink", keywords: "carrot" },
  { name: 'Salad', Icon: Salad, category: "Food & drink", keywords: "salad" },
  { name: 'Soup', Icon: Soup, category: "Food & drink", keywords: "soup" },
  { name: 'Beef', Icon: Beef, category: "Food & drink", keywords: "beef" },
  { name: 'Drumstick', Icon: Drumstick, category: "Food & drink", keywords: "drumstick" },
  { name: 'Ham', Icon: Ham, category: "Food & drink", keywords: "ham" },
  { name: 'Fish', Icon: Fish, category: "Food & drink", keywords: "fish" },
  { name: 'Egg', Icon: Egg, category: "Food & drink", keywords: "egg" },
  { name: 'EggFried', Icon: EggFried, category: "Food & drink", keywords: "egg fried" },
  { name: 'Pizza', Icon: Pizza, category: "Food & drink", keywords: "pizza" },
  { name: 'Sandwich', Icon: Sandwich, category: "Food & drink", keywords: "sandwich" },
  { name: 'Croissant', Icon: Croissant, category: "Food & drink", keywords: "croissant" },
  { name: 'Cake', Icon: Cake, category: "Food & drink", keywords: "cake" },
  { name: 'CakeSlice', Icon: CakeSlice, category: "Food & drink", keywords: "cake slice" },
  { name: 'Cookie', Icon: Cookie, category: "Food & drink", keywords: "cookie" },
  { name: 'Candy', Icon: Candy, category: "Food & drink", keywords: "candy" },
  { name: 'Donut', Icon: Donut, category: "Food & drink", keywords: "donut" },
  { name: 'IceCream', Icon: IceCream, category: "Food & drink", keywords: "ice cream" },
  { name: 'IceCreamCone', Icon: IceCreamCone, category: "Food & drink", keywords: "ice cream cone" },
  { name: 'Popcorn', Icon: Popcorn, category: "Food & drink", keywords: "popcorn" },
  { name: 'Wheat', Icon: Wheat, category: "Food & drink", keywords: "wheat" },
  { name: 'Milk', Icon: Milk, category: "Food & drink", keywords: "milk" },
  { name: 'Coffee', Icon: Coffee, category: "Food & drink", keywords: "coffee" },
  { name: 'CupSoda', Icon: CupSoda, category: "Food & drink", keywords: "cup soda" },
  { name: 'Wine', Icon: Wine, category: "Food & drink", keywords: "wine" },
  { name: 'Beer', Icon: Beer, category: "Food & drink", keywords: "beer" },
  { name: 'Martini', Icon: Martini, category: "Food & drink", keywords: "martini" },
  { name: 'GlassWater', Icon: GlassWater, category: "Food & drink", keywords: "glass water" },
  { name: 'Nut', Icon: Nut, category: "Food & drink", keywords: "nut" },
  { name: 'Bean', Icon: Bean, category: "Food & drink", keywords: "bean" },
  { name: 'Vegan', Icon: Vegan, category: "Food & drink", keywords: "vegan" },
  { name: 'ShoppingBag', Icon: ShoppingBag, category: "Shopping", keywords: "shopping bag" },
  { name: 'ShoppingCart', Icon: ShoppingCart, category: "Shopping", keywords: "shopping cart" },
  { name: 'ShoppingBasket', Icon: ShoppingBasket, category: "Shopping", keywords: "shopping basket" },
  { name: 'Store', Icon: Store, category: "Shopping", keywords: "store" },
  { name: 'Tag', Icon: Tag, category: "Shopping", keywords: "tag" },
  { name: 'Tags', Icon: Tags, category: "Shopping", keywords: "tags" },
  { name: 'Receipt', Icon: Receipt, category: "Shopping", keywords: "receipt" },
  { name: 'CreditCard', Icon: CreditCard, category: "Shopping", keywords: "credit card" },
  { name: 'Wallet', Icon: Wallet, category: "Shopping", keywords: "wallet" },
  { name: 'Gift', Icon: Gift, category: "Shopping", keywords: "gift" },
  { name: 'Package', Icon: Package, category: "Shopping", keywords: "package" },
  { name: 'PackageOpen', Icon: PackageOpen, category: "Shopping", keywords: "package open" },
  { name: 'Barcode', Icon: Barcode, category: "Shopping", keywords: "barcode" },
  { name: 'ScanBarcode', Icon: ScanBarcode, category: "Shopping", keywords: "scan barcode" },
  { name: 'Shirt', Icon: Shirt, category: "Shopping", keywords: "shirt" },
  { name: 'Footprints', Icon: Footprints, category: "Shopping", keywords: "footprints" },
  { name: 'Gem', Icon: Gem, category: "Shopping", keywords: "gem" },
  { name: 'Watch', Icon: Watch, category: "Shopping", keywords: "watch" },
  { name: 'Glasses', Icon: Glasses, category: "Shopping", keywords: "glasses" },
  { name: 'Crown', Icon: Crown, category: "Shopping", keywords: "crown" },
  { name: 'Plane', Icon: Plane, category: "Travel", keywords: "plane" },
  { name: 'PlaneTakeoff', Icon: PlaneTakeoff, category: "Travel", keywords: "plane takeoff" },
  { name: 'PlaneLanding', Icon: PlaneLanding, category: "Travel", keywords: "plane landing" },
  { name: 'Car', Icon: Car, category: "Travel", keywords: "car" },
  { name: 'CarFront', Icon: CarFront, category: "Travel", keywords: "car front" },
  { name: 'Bus', Icon: Bus, category: "Travel", keywords: "bus" },
  { name: 'Train', Icon: Train, category: "Travel", keywords: "train" },
  { name: 'TramFront', Icon: TramFront, category: "Travel", keywords: "tram front" },
  { name: 'Ship', Icon: Ship, category: "Travel", keywords: "ship" },
  { name: 'Sailboat', Icon: Sailboat, category: "Travel", keywords: "sailboat" },
  { name: 'Bike', Icon: Bike, category: "Travel", keywords: "bike" },
  { name: 'MapPin', Icon: MapPin, category: "Travel", keywords: "map pin" },
  { name: 'Map', Icon: Map, category: "Travel", keywords: "map" },
  { name: 'Globe', Icon: Globe, category: "Travel", keywords: "globe" },
  { name: 'Compass', Icon: Compass, category: "Travel", keywords: "compass" },
  { name: 'Luggage', Icon: Luggage, category: "Travel", keywords: "luggage" },
  { name: 'Briefcase', Icon: Briefcase, category: "Travel", keywords: "briefcase" },
  { name: 'Tent', Icon: Tent, category: "Travel", keywords: "tent" },
  { name: 'Mountain', Icon: Mountain, category: "Travel", keywords: "mountain" },
  { name: 'MountainSnow', Icon: MountainSnow, category: "Travel", keywords: "mountain snow" },
  { name: 'Palmtree', Icon: Palmtree, category: "Travel", keywords: "palmtree" },
  { name: 'TreePalm', Icon: TreePalm, category: "Travel", keywords: "tree palm" },
  { name: 'Sun', Icon: Sun, category: "Travel", keywords: "sun" },
  { name: 'Umbrella', Icon: Umbrella, category: "Travel", keywords: "umbrella" },
  { name: 'Camera', Icon: Camera, category: "Travel", keywords: "camera" },
  { name: 'Ticket', Icon: Ticket, category: "Travel", keywords: "ticket" },
  { name: 'Hotel', Icon: Hotel, category: "Travel", keywords: "hotel" },
  { name: 'Fuel', Icon: Fuel, category: "Travel", keywords: "fuel" },
  { name: 'ParkingCircle', Icon: ParkingCircle, category: "Travel", keywords: "parking circle" },
  { name: 'GraduationCap', Icon: GraduationCap, category: "Work & school", keywords: "graduation cap" },
  { name: 'BookOpen', Icon: BookOpen, category: "Work & school", keywords: "book open" },
  { name: 'Book', Icon: Book, category: "Work & school", keywords: "book" },
  { name: 'Library', Icon: Library, category: "Work & school", keywords: "library" },
  { name: 'PenTool', Icon: PenTool, category: "Work & school", keywords: "pen tool" },
  { name: 'Pencil', Icon: Pencil, category: "Work & school", keywords: "pencil" },
  { name: 'Pen', Icon: Pen, category: "Work & school", keywords: "pen" },
  { name: 'Ruler', Icon: Ruler, category: "Work & school", keywords: "ruler" },
  { name: 'Calculator', Icon: Calculator, category: "Work & school", keywords: "calculator" },
  { name: 'Laptop', Icon: Laptop, category: "Work & school", keywords: "laptop" },
  { name: 'Monitor', Icon: Monitor, category: "Work & school", keywords: "monitor" },
  { name: 'Presentation', Icon: Presentation, category: "Work & school", keywords: "presentation" },
  { name: 'Building', Icon: Building, category: "Work & school", keywords: "building" },
  { name: 'Building2', Icon: Building2, category: "Work & school", keywords: "building 2" },
  { name: 'Factory', Icon: Factory, category: "Work & school", keywords: "factory" },
  { name: 'Mailbox', Icon: Mailbox, category: "Work & school", keywords: "mailbox" },
  { name: 'Mail', Icon: Mail, category: "Work & school", keywords: "mail" },
  { name: 'Phone', Icon: Phone, category: "Work & school", keywords: "phone" },
  { name: 'Printer', Icon: Printer, category: "Work & school", keywords: "printer" },
  { name: 'Paperclip', Icon: Paperclip, category: "Work & school", keywords: "paperclip" },
  { name: 'Folder', Icon: Folder, category: "Work & school", keywords: "folder" },
  { name: 'FolderOpen', Icon: FolderOpen, category: "Work & school", keywords: "folder open" },
  { name: 'FileText', Icon: FileText, category: "Work & school", keywords: "file text" },
  { name: 'Files', Icon: Files, category: "Work & school", keywords: "files" },
  { name: 'Award', Icon: Award, category: "Work & school", keywords: "award" },
  { name: 'Trophy', Icon: Trophy, category: "Work & school", keywords: "trophy" },
  { name: 'Target', Icon: Target, category: "Work & school", keywords: "target" },
  { name: 'Microscope', Icon: Microscope, category: "Work & school", keywords: "microscope" },
  { name: 'FlaskConical', Icon: FlaskConical, category: "Work & school", keywords: "flask conical" },
  { name: 'Atom', Icon: Atom, category: "Work & school", keywords: "atom" },
  { name: 'Brain', Icon: Brain, category: "Work & school", keywords: "brain" },
  { name: 'Dumbbell', Icon: Dumbbell, category: "Health & fitness", keywords: "dumbbell" },
  { name: 'HeartPulse', Icon: HeartPulse, category: "Health & fitness", keywords: "heart pulse" },
  { name: 'Activity', Icon: Activity, category: "Health & fitness", keywords: "activity" },
  { name: 'PersonStanding', Icon: PersonStanding, category: "Health & fitness", keywords: "person standing" },
  { name: 'Pill', Icon: Pill, category: "Health & fitness", keywords: "pill" },
  { name: 'Stethoscope', Icon: Stethoscope, category: "Health & fitness", keywords: "stethoscope" },
  { name: 'Syringe', Icon: Syringe, category: "Health & fitness", keywords: "syringe" },
  { name: 'Cross', Icon: Cross, category: "Health & fitness", keywords: "cross" },
  { name: 'BriefcaseMedical', Icon: BriefcaseMedical, category: "Health & fitness", keywords: "briefcase medical" },
  { name: 'Eye', Icon: Eye, category: "Health & fitness", keywords: "eye" },
  { name: 'Bone', Icon: Bone, category: "Health & fitness", keywords: "bone" },
  { name: 'Moon', Icon: Moon, category: "Health & fitness", keywords: "moon" },
  { name: 'Droplet', Icon: Droplet, category: "Health & fitness", keywords: "droplet" },
  { name: 'Droplets', Icon: Droplets, category: "Health & fitness", keywords: "droplets" },
  { name: 'Flame', Icon: Flame, category: "Health & fitness", keywords: "flame" },
  { name: 'Timer', Icon: Timer, category: "Health & fitness", keywords: "timer" },
  { name: 'Medal', Icon: Medal, category: "Health & fitness", keywords: "medal" },
  { name: 'Heart', Icon: Heart, category: "Family & pets", keywords: "heart" },
  { name: 'Baby', Icon: Baby, category: "Family & pets", keywords: "baby" },
  { name: 'Users', Icon: Users, category: "Family & pets", keywords: "users" },
  { name: 'User', Icon: User, category: "Family & pets", keywords: "user" },
  { name: 'UserRound', Icon: UserRound, category: "Family & pets", keywords: "user round" },
  { name: 'CircleUserRound', Icon: CircleUserRound, category: "Family & pets", keywords: "circle user round" },
  { name: 'PawPrint', Icon: PawPrint, category: "Family & pets", keywords: "paw print" },
  { name: 'Dog', Icon: Dog, category: "Family & pets", keywords: "dog" },
  { name: 'Cat', Icon: Cat, category: "Family & pets", keywords: "cat" },
  { name: 'Bird', Icon: Bird, category: "Family & pets", keywords: "bird" },
  { name: 'Rabbit', Icon: Rabbit, category: "Family & pets", keywords: "rabbit" },
  { name: 'Turtle', Icon: Turtle, category: "Family & pets", keywords: "turtle" },
  { name: 'Bug', Icon: Bug, category: "Family & pets", keywords: "bug" },
  { name: 'Squirrel', Icon: Squirrel, category: "Family & pets", keywords: "squirrel" },
  { name: 'Rat', Icon: Rat, category: "Family & pets", keywords: "rat" },
  { name: 'Snail', Icon: Snail, category: "Family & pets", keywords: "snail" },
  { name: 'Smile', Icon: Smile, category: "Family & pets", keywords: "smile" },
  { name: 'HandHeart', Icon: HandHeart, category: "Family & pets", keywords: "hand heart" },
  { name: 'Handshake', Icon: Handshake, category: "Family & pets", keywords: "handshake" },
  { name: 'PartyPopper', Icon: PartyPopper, category: "Family & pets", keywords: "party popper" },
  { name: 'Gamepad2', Icon: Gamepad2, category: "Hobbies & leisure", keywords: "gamepad 2" },
  { name: 'Music', Icon: Music, category: "Hobbies & leisure", keywords: "music" },
  { name: 'Music2', Icon: Music2, category: "Hobbies & leisure", keywords: "music 2" },
  { name: 'Music4', Icon: Music4, category: "Hobbies & leisure", keywords: "music 4" },
  { name: 'Headphones', Icon: Headphones, category: "Hobbies & leisure", keywords: "headphones" },
  { name: 'Mic', Icon: Mic, category: "Hobbies & leisure", keywords: "mic" },
  { name: 'Guitar', Icon: Guitar, category: "Hobbies & leisure", keywords: "guitar" },
  { name: 'Piano', Icon: Piano, category: "Hobbies & leisure", keywords: "piano" },
  { name: 'Drum', Icon: Drum, category: "Hobbies & leisure", keywords: "drum" },
  { name: 'Radio', Icon: Radio, category: "Hobbies & leisure", keywords: "radio" },
  { name: 'Tv', Icon: Tv, category: "Hobbies & leisure", keywords: "tv" },
  { name: 'Film', Icon: Film, category: "Hobbies & leisure", keywords: "film" },
  { name: 'Clapperboard', Icon: Clapperboard, category: "Hobbies & leisure", keywords: "clapperboard" },
  { name: 'Image', Icon: Image, category: "Hobbies & leisure", keywords: "image" },
  { name: 'Palette', Icon: Palette, category: "Hobbies & leisure", keywords: "palette" },
  { name: 'PaintBucket', Icon: PaintBucket, category: "Hobbies & leisure", keywords: "paint bucket" },
  { name: 'Scissors', Icon: Scissors, category: "Hobbies & leisure", keywords: "scissors" },
  { name: 'Puzzle', Icon: Puzzle, category: "Hobbies & leisure", keywords: "puzzle" },
  { name: 'Dices', Icon: Dices, category: "Hobbies & leisure", keywords: "dices" },
  { name: 'Club', Icon: Club, category: "Hobbies & leisure", keywords: "club" },
  { name: 'Spade', Icon: Spade, category: "Hobbies & leisure", keywords: "spade" },
  { name: 'Diamond', Icon: Diamond, category: "Hobbies & leisure", keywords: "diamond" },
  { name: 'Flower', Icon: Flower, category: "Hobbies & leisure", keywords: "flower" },
  { name: 'Flower2', Icon: Flower2, category: "Hobbies & leisure", keywords: "flower 2" },
  { name: 'Sprout', Icon: Sprout, category: "Hobbies & leisure", keywords: "sprout" },
  { name: 'Cloud', Icon: Cloud, category: "Nature & weather", keywords: "cloud" },
  { name: 'CloudRain', Icon: CloudRain, category: "Nature & weather", keywords: "cloud rain" },
  { name: 'CloudSnow', Icon: CloudSnow, category: "Nature & weather", keywords: "cloud snow" },
  { name: 'CloudLightning', Icon: CloudLightning, category: "Nature & weather", keywords: "cloud lightning" },
  { name: 'Snowflake', Icon: Snowflake, category: "Nature & weather", keywords: "snowflake" },
  { name: 'Wind', Icon: Wind, category: "Nature & weather", keywords: "wind" },
  { name: 'Rainbow', Icon: Rainbow, category: "Nature & weather", keywords: "rainbow" },
  { name: 'Leaf', Icon: Leaf, category: "Nature & weather", keywords: "leaf" },
  { name: 'Trees', Icon: Trees, category: "Nature & weather", keywords: "trees" },
  { name: 'TreePine', Icon: TreePine, category: "Nature & weather", keywords: "tree pine" },
  { name: 'TreeDeciduous', Icon: TreeDeciduous, category: "Nature & weather", keywords: "tree deciduous" },
  { name: 'Waves', Icon: Waves, category: "Nature & weather", keywords: "waves" },
  { name: 'Sunrise', Icon: Sunrise, category: "Nature & weather", keywords: "sunrise" },
  { name: 'Sunset', Icon: Sunset, category: "Nature & weather", keywords: "sunset" },
  { name: 'Sparkles', Icon: Sparkles, category: "Nature & weather", keywords: "sparkles" },
  { name: 'Zap', Icon: Zap, category: "Nature & weather", keywords: "zap" },
  { name: 'Tornado', Icon: Tornado, category: "Nature & weather", keywords: "tornado" },
  { name: 'Smartphone', Icon: Smartphone, category: "Tech & devices", keywords: "smartphone" },
  { name: 'Tablet', Icon: Tablet, category: "Tech & devices", keywords: "tablet" },
  { name: 'Wifi', Icon: Wifi, category: "Tech & devices", keywords: "wifi" },
  { name: 'Bluetooth', Icon: Bluetooth, category: "Tech & devices", keywords: "bluetooth" },
  { name: 'Battery', Icon: Battery, category: "Tech & devices", keywords: "battery" },
  { name: 'Cpu', Icon: Cpu, category: "Tech & devices", keywords: "cpu" },
  { name: 'HardDrive', Icon: HardDrive, category: "Tech & devices", keywords: "hard drive" },
  { name: 'Database', Icon: Database, category: "Tech & devices", keywords: "database" },
  { name: 'Server', Icon: Server, category: "Tech & devices", keywords: "server" },
  { name: 'Mouse', Icon: Mouse, category: "Tech & devices", keywords: "mouse" },
  { name: 'Keyboard', Icon: Keyboard, category: "Tech & devices", keywords: "keyboard" },
  { name: 'Router', Icon: Router, category: "Tech & devices", keywords: "router" },
  { name: 'Usb', Icon: Usb, category: "Tech & devices", keywords: "usb" },
  { name: 'Webcam', Icon: Webcam, category: "Tech & devices", keywords: "webcam" },
  { name: 'Bot', Icon: Bot, category: "Tech & devices", keywords: "bot" },
  { name: 'Code', Icon: Code, category: "Tech & devices", keywords: "code" },
  { name: 'Terminal', Icon: Terminal, category: "Tech & devices", keywords: "terminal" },
  { name: 'Wrench', Icon: Wrench, category: "Tools & DIY", keywords: "wrench" },
  { name: 'Hammer', Icon: Hammer, category: "Tools & DIY", keywords: "hammer" },
  { name: 'Drill', Icon: Drill, category: "Tools & DIY", keywords: "drill" },
  { name: 'Axe', Icon: Axe, category: "Tools & DIY", keywords: "axe" },
  { name: 'Pickaxe', Icon: Pickaxe, category: "Tools & DIY", keywords: "pickaxe" },
  { name: 'Shovel', Icon: Shovel, category: "Tools & DIY", keywords: "shovel" },
  { name: 'PaintRoller', Icon: PaintRoller, category: "Tools & DIY", keywords: "paint roller" },
  { name: 'Pipette', Icon: Pipette, category: "Tools & DIY", keywords: "pipette" },
  { name: 'Cog', Icon: Cog, category: "Tools & DIY", keywords: "cog" },
  { name: 'Settings', Icon: Settings, category: "Tools & DIY", keywords: "settings" },
  { name: 'Bolt', Icon: Bolt, category: "Tools & DIY", keywords: "bolt" },
  { name: 'Magnet', Icon: Magnet, category: "Tools & DIY", keywords: "magnet" },
  { name: 'Construction', Icon: Construction, category: "Tools & DIY", keywords: "construction" },
  { name: 'HardHat', Icon: HardHat, category: "Tools & DIY", keywords: "hard hat" },
  { name: 'Banknote', Icon: Banknote, category: "Money", keywords: "banknote" },
  { name: 'Coins', Icon: Coins, category: "Money", keywords: "coins" },
  { name: 'DollarSign', Icon: DollarSign, category: "Money", keywords: "dollar sign" },
  { name: 'PiggyBank', Icon: PiggyBank, category: "Money", keywords: "piggy bank" },
  { name: 'Landmark', Icon: Landmark, category: "Money", keywords: "landmark" },
  { name: 'TrendingUp', Icon: TrendingUp, category: "Money", keywords: "trending up" },
  { name: 'TrendingDown', Icon: TrendingDown, category: "Money", keywords: "trending down" },
  { name: 'BadgeDollarSign', Icon: BadgeDollarSign, category: "Money", keywords: "badge dollar sign" },
  { name: 'HandCoins', Icon: HandCoins, category: "Money", keywords: "hand coins" },
  { name: 'CircleDollarSign', Icon: CircleDollarSign, category: "Money", keywords: "circle dollar sign" },
  { name: 'Rocket', Icon: Rocket, category: "Symbols & misc", keywords: "rocket" },
  { name: 'Anchor', Icon: Anchor, category: "Symbols & misc", keywords: "anchor" },
  { name: 'Feather', Icon: Feather, category: "Symbols & misc", keywords: "feather" },
  { name: 'Infinity', Icon: Infinity, category: "Symbols & misc", keywords: "infinity" },
  { name: 'ThumbsUp', Icon: ThumbsUp, category: "Symbols & misc", keywords: "thumbs up" },
  { name: 'Check', Icon: Check, category: "Symbols & misc", keywords: "check" },
  { name: 'CircleCheck', Icon: CircleCheck, category: "Symbols & misc", keywords: "circle check" },
  { name: 'Circle', Icon: Circle, category: "Symbols & misc", keywords: "circle" },
  { name: 'Square', Icon: Square, category: "Symbols & misc", keywords: "square" },
  { name: 'Triangle', Icon: Triangle, category: "Symbols & misc", keywords: "triangle" },
  { name: 'Hexagon', Icon: Hexagon, category: "Symbols & misc", keywords: "hexagon" },
  { name: 'Shield', Icon: Shield, category: "Symbols & misc", keywords: "shield" },
  { name: 'Lock', Icon: Lock, category: "Symbols & misc", keywords: "lock" },
  { name: 'Unlock', Icon: Unlock, category: "Symbols & misc", keywords: "unlock" },
  { name: 'Search', Icon: Search, category: "Symbols & misc", keywords: "search" },
  { name: 'Filter', Icon: Filter, category: "Symbols & misc", keywords: "filter" },
  { name: 'Wand2', Icon: Wand2, category: "Symbols & misc", keywords: "wand 2" },
  { name: 'Crosshair', Icon: Crosshair, category: "Symbols & misc", keywords: "crosshair" },
  { name: 'Hourglass', Icon: Hourglass, category: "Symbols & misc", keywords: "hourglass" },
  { name: 'Calendar', Icon: Calendar, category: "Symbols & misc", keywords: "calendar" },
];

// NB: `Map` is shadowed by the Lucide `Map` icon imported above, so we build the
// lookup as a plain record rather than with the Map constructor.
const ICON_BY_NAME: Record<string, ListIconType> = Object.fromEntries(
  ICON_OPTIONS.map((o) => [o.name, o.Icon]),
);

/**
 * Resolve a list's stored icon name to its Lucide component.
 * Falls back to ListChecks for unknown / legacy names.
 */
export function getListIcon(iconName: string | null): ListIconType {
  return (iconName && ICON_BY_NAME[iconName]) || ListChecks;
}
